markdown: kramdown
permalink: /:year/:month/:title/
github: westerly-lzh
url: http://westerly-lzh.github.io/cn
author: Jeff Lee
name: Jeff Lee
email: westerly.lzh@gmail.com
highlighter: pygments
safe: true


#markdown: rdiscount
#permalink: /:year/:month/:title/
#url: http://westerly-lzh.github.io/cn
#author: Jeff Lee
#pygments: true

