markdown: kramdown
permalink: /:year/:month/:title/
github: westerly-lzh
url: http://jeff-lee.name/cn
author: Jeff Lee
name: Jeff Lee
email: westerly.lzh@gmail.com
pygments: true
safe: true


#markdown: rdiscount
#permalink: /:year/:month/:title/
#url: http://jeff-lee.name/cn
#author: Jeff Lee
#pygments: true

